### PR TITLE
Update to yarn berry, remove debug on pwa

### PR DESCRIPTION
**Pull request by CodeDoctorDE**
Yarn berry is faster and is active mantained: https://github.com/yarnpkg/berry
I removed debug from pwa plugin because it shouldn't be active in a production environment.

### CODE REVIEW

**Comment by CodeDoctorDE** [comment]
Strange...
On my local machine it works
```
[SUCCESS] Generated static files in build.
[INFO] Use `npm run serve` command to test your build locally.
```

**Comment by CodeDoctorDE** [comment]
It's very fast and and is recommend by the maintainers of yarn https://yarnpkg.com/getting-started/migration#why-should-you-migrate

The only disadvantage that I saw is, that dependabot isn't working correct with the package format. Maybe the deployment has failed because of the new commands?
```
yarn upgrade -> yarn up
yarn outdated -> yarn upgrade-interactive
```

**Comment by leisim** [comment]
I think this is not needed any more after the switch to vuepress

**Comment by CodeDoctorDE** [comment]
Now you are using the npm. It's slower than the normal yarn.

**Comment by leisim** [comment]
Hahaha it doesn't matter

**Pull request closed without merging**
